---
- name: Golang | Install go
  script: scripts/install.sh
  become: yes
  args:
    creates: "{{ golang.prefix }}/go/bin"
  
- name: Golang | Copy golang.zshrc
  template:
    src: templates/golang.zshrc.j2
    dest: "{{ zsh.dotfile_path }}/golang.zshrc"

- name: Golang | Install global golang packages
  command: "{{ golang.prefix }}/go/bin/go get '{{item}}'"
  args:
    creates: "{{ golang.gopath }}/src/{{item}}"
  environment:
    GOPATH: "{{ golang.gopath }}"
  with_items:
    - "{{ packages.golang }}"
