---
- hosts: test
  become: no

  vars_files:
    - vars/common.yml
    - vars/macos.yml

  roles:
#    - role: elliotweiser.osx-command-line-tools
#    - role: geerlingguy.homebrew
#    - role: git
    - role: zsh
#    - role: package
    - role: nodejs
