---
- hosts: macOS
  become: no

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
    - role: package
    - role: git
    - role: zsh
    - role: coreutils
    - role: nodejs
    - role: golang
    - role: macos
