---
- name: NodeJS | Install global packages
  npm:
    name: "{{ item }}"
    global: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ nodejs.n_install_path }}/bin"
  with_items:
    - "{{ packages.npm }}"
