---
- name: NodeJS | Setup .npmrc
  template: >
    src=templates/npmrc.j2
    dest=~/.npmrc

- name: NodeJS | Copy nodejs.zshrc
  template: >
    src=templates/nodejs.zshrc.j2
    dest={{ zsh.dotfile_path }}/nodejs.zshrc

- name: NodeJS | Check if n is already installed
  stat: path={{ nodejs.n_install_path }}
  register: nodejs_n_dir

- name: NodeJS | Install n
  shell: "curl -sL https://git.io/n-install | bash -s -- -n -y"
  environment:
    N_PREFIX: "{{ nodejs.n_install_path }}"
  args:
    warn: no
    creates: "{{ nodejs.n_install_path }}"
  when: nodejs_n_dir.stat.exists == False

- name: NodeJS | Install requested NodeJS versions
  command: "{{ nodejs.n_install_path }}/bin/n {{ item }}"
  environment:
    N_PREFIX: "{{ nodejs.n_install_path }}"
  with_items:
    - "{{ nodejs.versions }}"
  when: nodejs_n_dir.stat.exists == False
