---
- name: ZSH | Check if antibody is already installed
  stat: path=/usr/local/bin/antibody
  register: zsh_antibody_binary

- name: ZSH | Install antibody
  shell: "curl -sL https://git.io/antibody | bash -s"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  args:
    warn: no
  become: yes
  when: zsh_antibody_binary.stat.exists == False

- name: ZSH | Copy antibody.zshrc
  template: >
    src=templates/antibody.zshrc.j2
    dest={{ zsh.dotfile_path }}/antibody.zshrc
