---
- name: ZSH | Create .zsh directory
  file: >
    path={{ zsh.dotfile_path }}
    state=directory

- name: ZSH | Create .zsh/bin directory
  file:
    path: "{{ zsh.dotfile_path }}/bin"
    state: directory

- name: ZSH | Set default shell for remote user to zsh
  user: >
    name={{ ansible_user_id }}
    shell=/bin/zsh
  become: yes

- name: ZSH | Copy .zshrc
  template: >
    src=templates/zshrc.j2
    dest=~/.zshrc

- include_tasks: antibody.yml
