---
#
# Pulls SSL certificates from the S3 bucket and put them into /etc/ssl/private
# Requires the host to be in "webserver" group.
#
- name: SSL | Pull SSL certificate from S3
  become: yes
  aws_s3:
    aws_access_key: "{{ cert_puller.aws_access_key }}"
    aws_secret_key: "{{ cert_puller.aws_secret_key }}"
    bucket: "{{ cert_puller.bucket }}"
    object: "{{ item }}/fullchain.cer"
    dest: "/etc/ssl/private/{{ item }}.cer"
    mode: get
  with_items: "{{ cert_puller.domains }}"
  when: '"webserver" in group_names'

- name: SSL | Pull SSL certificate key from S3
  become: yes
  aws_s3:
    aws_access_key: "{{ cert_puller.aws_access_key }}"
    aws_secret_key: "{{ cert_puller.aws_secret_key }}"
    bucket: "{{ cert_puller.bucket }}"
    object: "{{ item }}/{{ item }}.key"
    dest: "/etc/ssl/private/{{ item }}.key"
    mode: get
  with_items: "{{ cert_puller.domains }}"
  when: '"webserver" in group_names'
